/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListChatResponse } from '../../models/api-response-list-chat-response';

export interface GetChatsByReceiver$Params {
}

export function getChatsByReceiver(http: HttpClient, rootUrl: string, params?: GetChatsByReceiver$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListChatResponse>> {
  const rb = new RequestBuilder(rootUrl, getChatsByReceiver.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListChatResponse>;
    })
  );
}

getChatsByReceiver.PATH = '/api/v1/chats';
