/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface ApiResponseListUserDto {
  data?: Array<UserDto>;
  message?: string;
  statusCode?: number;
  timestamp?: string;
}
