/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatResponse } from '../models/chat-response';
export interface ApiResponseListChatResponse {
  data?: Array<ChatResponse>;
  message?: string;
  statusCode?: number;
  timestamp?: string;
}
