/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageResponse } from '../models/message-response';
export interface ApiResponseListMessageResponse {
  data?: Array<MessageResponse>;
  message?: string;
  statusCode?: number;
  timestamp?: string;
}
