/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiResponseString {
  data?: string;
  message?: string;
  statusCode?: number;
  timestamp?: string;
}
