/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  email?: string;
  emailVerified?: boolean;
  firstName?: string;
  id?: string;
  lastName?: string;
  username?: string;
}
